Create Update servers PR

diff --git a/azure-pipelines-update-servers.yaml b/azure-pipelines-update-servers.yaml
--- a/azure-pipelines-update-servers.yaml
+++ b/azure-pipelines-update-servers.yaml
@@ -21,6 +21,8 @@ variables:
     value: $(System.DefaultWorkingDirectory)/data/static_backends/cww.yaml
   - name: branch_name
     value: automatic_servers_update
+  - name: target_branch
+    value: master
 
 pool: cicd-v2
 
@@ -59,75 +61,82 @@ steps:
       git config --global user.email $(email)
     displayName: "Configure git globals"
 
-  - task: DownloadPipelineArtifact@2
-    displayName: 'Download dante artifact'
-    inputs:
-      buildType: 'specific'
-      project: 'InfrastructureAutomation'
-      # dante build artifact pipeline Id
-      pipeline: 26
-      buildVersionToDownload: 'specific'
-      buildId: '$(dante_build_id)'
-      path: $(Build.SourcesDirectory)
-
-  - task: CopyFiles@2
-    displayName: 'Merge artifacts to a single roles folder'
-    inputs:
-      sourceFolder: iris
-      targetFolder: ansible
-
-  - task: AzureKeyVault@2
-    displayName: 'Get secrets from Azure KV'
-    inputs:
-      azureSubscription: 'sc-azuredevops2dante-vaults'
-      KeyVaultName: $(azure_kv_name)
-      SecretsFilter: secretAppIdDf4b4604e176
-      RunAsPreJob: false
-
-  - task: Ansible@0
-    displayName: 'Update servers'
-    inputs:
-      ansibleInterface: 'agentMachine'
-      playbookPathOnAgentMachine: 'ansible/update_servers.yaml'
-      failOnStdErr: false
-      args: >-
-        --diff
-        -e="azure_kv_name=$(azure_kv_name)"
-    env:
-      secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
-
   - script: |
       set -euxo pipefail
-      git fetch origin master
-      git checkout -b $(branch_name) origin/master
-    displayName: Create new branch
+      git fetch origin $(target_branch)
+      git branch -D $(branch_name) 2>/dev/null || true
+      git checkout -b $(branch_name) origin/$(target_branch)
+    displayName: "Create and checkout branch"
 
-  - script: |
-      set -euxo pipefail
-      if [[ $(echo $(upgrade_files) | xargs git status --porcelain) ]]; then
-        git add $(upgrade_files)
-        git commit -m "Automated Push of $(branch_name)"
-      else
-        echo -n "$(date) INFO - There is no difference between commits."
-        set +x
-        echo "##vso[task.setvariable variable=changed]no"
-        exit 0
-      fi
-      git push -f origin $(branch_name)
-      echo -n "$(date) INFO - There is a difference between commits. Attempt to create PR."
-      set +x
-      echo "##vso[task.setvariable variable=changed]yes"
-    displayName: Push Commit
+  # - task: DownloadPipelineArtifact@2
+  #   displayName: 'Download dante artifact'
+  #   inputs:
+  #     buildType: 'specific'
+  #     project: 'InfrastructureAutomation'
+  #     # dante build artifact pipeline Id
+  #     pipeline: 26
+  #     buildVersionToDownload: 'specific'
+  #     buildId: '$(dante_build_id)'
+  #     path: $(Build.SourcesDirectory)
 
-  - script: |
-      az repos pr list --source-branch $(branch_name) | jq -e '.[0]'
-      if [[ $? -ne 0 ]]; then
-        az repos pr create --auto-complete true --repository $(repository) \
-        --source-branch $(branch_name) \
-        --target-branch master --delete-source-branch true --title "Automated Servers update"
-        exit 0
-      else
-        echo "No PR created as it already exists"
-      fi
-    condition: and(succeeded(), eq(variables['changed'], 'yes'))
-    displayName: Create PR and Set Auto-Complete
+  # - task: CopyFiles@2
+  #   displayName: 'Merge artifacts to a single roles folder'
+  #   inputs:
+  #     sourceFolder: iris
+  #     targetFolder: ansible
+
+  # - task: AzureKeyVault@2
+  #   displayName: 'Get secrets from Azure KV'
+  #   inputs:
+  #     azureSubscription: 'sc-azuredevops2dante-vaults'
+  #     KeyVaultName: $(azure_kv_name)
+  #     SecretsFilter: secretAppIdDf4b4604e176
+  #     RunAsPreJob: false
+
+  # - task: Ansible@0
+  #   displayName: 'Update servers'
+  #   inputs:
+  #     ansibleInterface: 'agentMachine'
+  #     playbookPathOnAgentMachine: 'ansible/update_servers.yaml'
+  #     failOnStdErr: false
+  #     args: >-
+  #       --diff
+  #       -e="azure_kv_name=$(azure_kv_name)"
+  #   env:
+  #     secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
+
+  # - script: |
+  #     set -euxo pipefail
+  #     git fetch origin master
+  #     git checkout -b $(branch_name) origin/master
+  #   displayName: Create new branch
+
+  # - script: |
+  #     set -euxo pipefail
+  #     if [[ $(echo $(upgrade_files) | xargs git status --porcelain) ]]; then
+  #       git add $(upgrade_files)
+  #       git commit -m "Automated Push of $(branch_name)"
+  #     else
+  #       echo -n "$(date) INFO - There is no difference between commits."
+  #       set +x
+  #       echo "##vso[task.setvariable variable=changed]no"
+  #       exit 0
+  #     fi
+  #     git push -f origin $(branch_name)
+  #     echo -n "$(date) INFO - There is a difference between commits. Attempt to create PR."
+  #     set +x
+  #     echo "##vso[task.setvariable variable=changed]yes"
+  #   displayName: Push Commit
+
+  # - script: |
+  #     az repos pr list --source-branch $(branch_name) | jq -e '.[0]'
+  #     if [[ $? -ne 0 ]]; then
+  #       az repos pr create --auto-complete true --repository $(repository) \
+  #       --source-branch $(branch_name) \
+  #       --target-branch master --delete-source-branch true --title "Automated Servers update"
+  #       exit 0
+  #     else
+  #       echo "No PR created as it already exists"
+  #     fi
+  #   condition: and(succeeded(), eq(variables['changed'], 'yes'))
+  #   displayName: Create PR and Set Auto-Complete
