Python fixes

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -87,204 +87,204 @@ stages:
             displayName: 'Ansible lint'
             condition: succeededOrFailed()
 
-  - stage: Simulations
-    dependsOn: [Tests_and_lint]
-    pool:
-      name: simulations
-      demands:
-        - ALLOW_HEAVY_LOADS -equals yes
-    jobs:
-      - job: Simulation
-        strategy:
-          matrix:
-            AU2:
-              simulation_dc: AU2
-              s3_host: au2s3-2.wtg.ws
-              s3_iris_bucket: s3://au-iscore-iris-prod-1/
-              pure_usernames: au-iscore-iris-prod-1-ro
-            DE1:
-              simulation_dc: DE1
-              s3_host: de1s3-2.wtg.ws
-              s3_iris_bucket: s3://de-iscore-iris-prod-1/
-              pure_usernames: de-iscore-iris-prod-1-ro
-            US2:
-              simulation_dc: US2
-              s3_host: us2s3-2.wtg.ws
-              s3_iris_bucket: s3://us-iscore-iris-prod-1/
-              pure_usernames: us-iscore-iris-prod-1-ro
-            CN1:
-              simulation_dc: CN1
-              s3_host: au2s3-2.wtg.ws
-              s3_iris_bucket: s3://au-iscore-iris-prod-1/
-              pure_usernames: au-iscore-iris-prod-1-ro
-            SA1:
-              simulation_dc: SA1
-              s3_host: au2s3-2.wtg.ws
-              s3_iris_bucket: s3://au-iscore-iris-prod-1/
-              pure_usernames: au-iscore-iris-prod-1-ro
-        steps:
-          - checkout: master_branch
-            path: master_worktree
-            clean: false
-            displayName: 'Checkout master branch to master_worktree'
+  # - stage: Simulations
+  #   dependsOn: [Tests_and_lint]
+  #   pool:
+  #     name: simulations
+  #     demands:
+  #       - ALLOW_HEAVY_LOADS -equals yes
+  #   jobs:
+  #     - job: Simulation
+  #       strategy:
+  #         matrix:
+  #           AU2:
+  #             simulation_dc: AU2
+  #             s3_host: au2s3-2.wtg.ws
+  #             s3_iris_bucket: s3://au-iscore-iris-prod-1/
+  #             pure_usernames: au-iscore-iris-prod-1-ro
+  #           DE1:
+  #             simulation_dc: DE1
+  #             s3_host: de1s3-2.wtg.ws
+  #             s3_iris_bucket: s3://de-iscore-iris-prod-1/
+  #             pure_usernames: de-iscore-iris-prod-1-ro
+  #           US2:
+  #             simulation_dc: US2
+  #             s3_host: us2s3-2.wtg.ws
+  #             s3_iris_bucket: s3://us-iscore-iris-prod-1/
+  #             pure_usernames: us-iscore-iris-prod-1-ro
+  #           CN1:
+  #             simulation_dc: CN1
+  #             s3_host: au2s3-2.wtg.ws
+  #             s3_iris_bucket: s3://au-iscore-iris-prod-1/
+  #             pure_usernames: au-iscore-iris-prod-1-ro
+  #           SA1:
+  #             simulation_dc: SA1
+  #             s3_host: au2s3-2.wtg.ws
+  #             s3_iris_bucket: s3://au-iscore-iris-prod-1/
+  #             pure_usernames: au-iscore-iris-prod-1-ro
+  #       steps:
+  #         - checkout: master_branch
+  #           path: master_worktree
+  #           clean: false
+  #           displayName: 'Checkout master branch to master_worktree'
 
-          - checkout: self
-            path: s/iris
-            clean: false
-            displayName: 'Checkout self'
+  #         - checkout: self
+  #           path: s/iris
+  #           clean: false
+  #           displayName: 'Checkout self'
 
-          - task: AzureKeyVault@2
-            displayName: 'Get secret to authenticate to key vault from ansible'
-            inputs:
-              azureSubscription: 'sc-azuredevops2dante-vaults'
-              KeyVaultName: kv-wtg-dante-sim
-              SecretsFilter: secretAppIdDf4b4604e176
+  #         - task: AzureKeyVault@2
+  #           displayName: 'Get secret to authenticate to key vault from ansible'
+  #           inputs:
+  #             azureSubscription: 'sc-azuredevops2dante-vaults'
+  #             KeyVaultName: kv-wtg-dante-sim
+  #             SecretsFilter: secretAppIdDf4b4604e176
 
-          - script: |
-              set -euxo pipefail
-              pip install -r iris/requirements.txt
-            displayName: 'Install requirements'
+  #         - script: |
+  #             set -euxo pipefail
+  #             pip install -r iris/requirements.txt
+  #           displayName: 'Install requirements'
 
-          - script: |
-              set -euxo pipefail
-              cp iris/ansible/ansible.cfg .
-            displayName: 'Prepare to run playbooks'
+  #         - script: |
+  #             set -euxo pipefail
+  #             cp iris/ansible/ansible.cfg .
+  #           displayName: 'Prepare to run playbooks'
 
-          - task: DownloadPipelineArtifact@2
-            displayName: 'Download dante artifact'
-            inputs:
-              buildType: 'specific'
-              project: 'InfrastructureAutomation'
-              # dante build artifact pipeline Id
-              pipeline: 26
-              buildVersionToDownload: 'specific'
-              buildId: '$(dante_build_id)'
-              path: $(Build.SourcesDirectory)/dante
+  #         - task: DownloadPipelineArtifact@2
+  #           displayName: 'Download dante artifact'
+  #           inputs:
+  #             buildType: 'specific'
+  #             project: 'InfrastructureAutomation'
+  #             # dante build artifact pipeline Id
+  #             pipeline: 26
+  #             buildVersionToDownload: 'specific'
+  #             buildId: '$(dante_build_id)'
+  #             path: $(Build.SourcesDirectory)/dante
 
-          - task: DownloadPipelineArtifact@2
-            displayName: 'Download sqlbilling artifacts for ACL'
-            inputs:
-              buildType: 'specific'
-              project: 'ISOperations'
-              # https://dev.azure.com/WTGOps/ISOperations/_build?definitionId=239
-              pipeline: 239
-              artifact: sqlbilling
-              buildVersionToDownload: 'specific'
-              buildId: '$(sqlbilling_build_id)'
-              path: $(Build.SourcesDirectory)/sqlbilling_acl
-              patterns: 'acl/*.acl'
+  #         - task: DownloadPipelineArtifact@2
+  #           displayName: 'Download sqlbilling artifacts for ACL'
+  #           inputs:
+  #             buildType: 'specific'
+  #             project: 'ISOperations'
+  #             # https://dev.azure.com/WTGOps/ISOperations/_build?definitionId=239
+  #             pipeline: 239
+  #             artifact: sqlbilling
+  #             buildVersionToDownload: 'specific'
+  #             buildId: '$(sqlbilling_build_id)'
+  #             path: $(Build.SourcesDirectory)/sqlbilling_acl
+  #             patterns: 'acl/*.acl'
 
-          - task: CopyFiles@2
-            displayName: 'Merge artifacts to a single roles folder'
-            inputs:
-              sourceFolder: dante/iris
-              targetFolder: iris/ansible
+  #         - task: CopyFiles@2
+  #           displayName: 'Merge artifacts to a single roles folder'
+  #           inputs:
+  #             sourceFolder: dante/iris
+  #             targetFolder: iris/ansible
 
-          - task: InstallSSHKey@0
-            displayName: 'Install an SSH key'
-            inputs:
-              knownHostsEntry: 'StrictHostKeyChecking no'
-              sshKeySecureFile: 'id_rsa'
+  #         - task: InstallSSHKey@0
+  #           displayName: 'Install an SSH key'
+  #           inputs:
+  #             knownHostsEntry: 'StrictHostKeyChecking no'
+  #             sshKeySecureFile: 'id_rsa'
 
-          - script: |
-              set -euxo pipefail
+  #         - script: |
+  #             set -euxo pipefail
 
-              echo "##vso[task.setvariable variable=certificate_changed]true"
+  #             echo "##vso[task.setvariable variable=certificate_changed]true"
 
-              DC_LOWER=$(echo "$(simulation_dc)" | tr '[:upper:]' '[:lower:]')
+  #             DC_LOWER=$(echo "$(simulation_dc)" | tr '[:upper:]' '[:lower:]')
 
-              # Extract certificates from instance definition file
-              yq '.clustered_instances.hosts[].certificates[]?' \
-              iris/data/instances/${DC_LOWER}-clustered_instances.yml > pr_certs.yml || true
+  #             # Extract certificates from instance definition file
+  #             yq '.clustered_instances.hosts[].certificates[]?' \
+  #             iris/data/instances/${DC_LOWER}-clustered_instances.yml > pr_certs.yml || true
 
-              yq '.clustered_instances.hosts[].certificates[]?' \
-              ../master_worktree/data/instances/${DC_LOWER}-clustered_instances.yml > master_certs.yml || true
+  #             yq '.clustered_instances.hosts[].certificates[]?' \
+  #             ../master_worktree/data/instances/${DC_LOWER}-clustered_instances.yml > master_certs.yml || true
 
-              # Check the difference
-              if diff -q master_certs.yml pr_certs.yml >/dev/null 2>&1; then
-                echo "Certificates unchanged in ${DC_LOWER}-clustered_instances.yml"
-                echo "##vso[task.setvariable variable=certificate_changed]false"
-              else
-                echo "Certificates changed in ${DC_LOWER}-clustered_instances.yml"
-              fi
-            displayName: 'Check if the certificate section changed'
+  #             # Check the difference
+  #             if diff -q master_certs.yml pr_certs.yml >/dev/null 2>&1; then
+  #               echo "Certificates unchanged in ${DC_LOWER}-clustered_instances.yml"
+  #               echo "##vso[task.setvariable variable=certificate_changed]false"
+  #             else
+  #               echo "Certificates changed in ${DC_LOWER}-clustered_instances.yml"
+  #             fi
+  #           displayName: 'Check if the certificate section changed'
 
-          - task: Ansible@0
-            displayName: 'Check and save certificates'
-            inputs:
-              ansibleInterface: 'agentMachine'
-              playbookPathOnAgentMachine: 'iris/ansible/check_and_save_certificates_cms.yml'
-              inventoriesAgentMachine: 'file'
-              inventoryFileOnAgentMachine: 'iris/data/instances'
-              failOnStdErr: false
-              args: >-
-                -u $(user) --diff
-                -e="azure_kv_name=$(azure_kv_name)"
-                -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
-                -e="s3_host=$(s3_host)" -e="pure_usernames=$(pure_usernames)"
-                -e="s3_iris_bucket=$(s3_iris_bucket)"
-                -e "{check_all_certs: $(certificate_changed) }"
-                -e "{use_cache: $(cms_use_cache)}"
-                -e="{simulation: true}" -e="azure_kv_name=$(azure_kv_name)"
-            env:
-              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
+  #         - task: Ansible@0
+  #           displayName: 'Check and save certificates'
+  #           inputs:
+  #             ansibleInterface: 'agentMachine'
+  #             playbookPathOnAgentMachine: 'iris/ansible/check_and_save_certificates_cms.yml'
+  #             inventoriesAgentMachine: 'file'
+  #             inventoryFileOnAgentMachine: 'iris/data/instances'
+  #             failOnStdErr: false
+  #             args: >-
+  #               -u $(user) --diff
+  #               -e="azure_kv_name=$(azure_kv_name)"
+  #               -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
+  #               -e="s3_host=$(s3_host)" -e="pure_usernames=$(pure_usernames)"
+  #               -e="s3_iris_bucket=$(s3_iris_bucket)"
+  #               -e "{check_all_certs: $(certificate_changed) }"
+  #               -e "{use_cache: $(cms_use_cache)}"
+  #               -e="{simulation: true}" -e="azure_kv_name=$(azure_kv_name)"
+  #           env:
+  #             secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
 
-          - task: Bash@3
-            displayName: 'Test haproxy'
-            inputs:
-              targetType: 'inline'
-              script: |
-                set -euo pipefail
-                exec ansible-playbook \
-                  iris/ansible/test_haproxy.yml \
-                  -i iris/data/instances \
-                  -u $(user) \
-                  -e="azure_kv_name=$(azure_kv_name)" \
-                  -e="build_id=$(Build.BuildId)$(System.JobAttempt)" \
-                  -e="{instance_auto_restart_allowed: $(instance_auto_restart_allowed)}" \
-                  -e="s3_host=$(s3_host)" -e="pure_usernames=$(pure_usernames)" \
-                  -e="s3_iris_bucket=$(s3_iris_bucket)" \
-                  -e="s3_proxy_host=192.168.255.254" -e="s3_proxy_port=3128" \
-                  -e="sqlbilling_acl_dir=$(Build.SourcesDirectory)/sqlbilling_acl/acl" \
-                  -e="target_dc=$(simulation_dc)" \
-                  -e="apt_mirror=$(apt_mirror)" \
-                  -e "{check_all_certs: $(certificate_changed) }" \
-                  -e "{simulation: true}"
-            env:
-              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
-              ANSIBLE_DISPLAY_SKIPPED_HOSTS: $(ansible_display_skipped_hosts)
-              ANSIBLE_DISPLAY_OK_HOSTS: $(ansible_display_ok_hosts)
-              ANSIBLE_DIFF_ALWAYS: $(ansible_diff_always)
+  #         - task: Bash@3
+  #           displayName: 'Test haproxy'
+  #           inputs:
+  #             targetType: 'inline'
+  #             script: |
+  #               set -euo pipefail
+  #               exec ansible-playbook \
+  #                 iris/ansible/test_haproxy.yml \
+  #                 -i iris/data/instances \
+  #                 -u $(user) \
+  #                 -e="azure_kv_name=$(azure_kv_name)" \
+  #                 -e="build_id=$(Build.BuildId)$(System.JobAttempt)" \
+  #                 -e="{instance_auto_restart_allowed: $(instance_auto_restart_allowed)}" \
+  #                 -e="s3_host=$(s3_host)" -e="pure_usernames=$(pure_usernames)" \
+  #                 -e="s3_iris_bucket=$(s3_iris_bucket)" \
+  #                 -e="s3_proxy_host=192.168.255.254" -e="s3_proxy_port=3128" \
+  #                 -e="sqlbilling_acl_dir=$(Build.SourcesDirectory)/sqlbilling_acl/acl" \
+  #                 -e="target_dc=$(simulation_dc)" \
+  #                 -e="apt_mirror=$(apt_mirror)" \
+  #                 -e "{check_all_certs: $(certificate_changed) }" \
+  #                 -e "{simulation: true}"
+  #           env:
+  #             secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
+  #             ANSIBLE_DISPLAY_SKIPPED_HOSTS: $(ansible_display_skipped_hosts)
+  #             ANSIBLE_DISPLAY_OK_HOSTS: $(ansible_display_ok_hosts)
+  #             ANSIBLE_DIFF_ALWAYS: $(ansible_diff_always)
 
-          - publish: $(Build.SourcesDirectory)/iris/generated_configs/$(simulation_dc)
-            artifact: configs_$(simulation_dc)_attempt$(System.JobAttempt)
-            displayName: 'Publish configs for $(simulation_dc)'
-            condition: always()
+  #         - publish: $(Build.SourcesDirectory)/iris/generated_configs/$(simulation_dc)
+  #           artifact: configs_$(simulation_dc)_attempt$(System.JobAttempt)
+  #           displayName: 'Publish configs for $(simulation_dc)'
+  #           condition: always()
 
-          - task: Ansible@0
-            displayName: 'Unregister nodes'
-            inputs:
-              ansibleInterface: 'agentMachine'
-              playbookPathOnAgentMachine: 'iris/ansible/unregister_nodes.yaml'
-              inventoriesAgentMachine: 'file'
-              inventoryFileOnAgentMachine: 'iris/data/instances'
-              failOnStdErr: false
-              args: >-
-                -u $(user) --diff
-                -e="azure_kv_name=$(azure_kv_name)"
-                -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
-                -e="target_dc=$(simulation_dc)"
-                -e "{simulation: true}"
-            env:
-              secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
-            condition: always()
+  #         - task: Ansible@0
+  #           displayName: 'Unregister nodes'
+  #           inputs:
+  #             ansibleInterface: 'agentMachine'
+  #             playbookPathOnAgentMachine: 'iris/ansible/unregister_nodes.yaml'
+  #             inventoriesAgentMachine: 'file'
+  #             inventoryFileOnAgentMachine: 'iris/data/instances'
+  #             failOnStdErr: false
+  #             args: >-
+  #               -u $(user) --diff
+  #               -e="azure_kv_name=$(azure_kv_name)"
+  #               -e="build_id=$(Build.BuildId)$(System.JobAttempt)"
+  #               -e="target_dc=$(simulation_dc)"
+  #               -e "{simulation: true}"
+  #           env:
+  #             secretAppIdDf4b4604e176: $(secretAppIdDf4b4604e176)
+  #           condition: always()
 
-          - task: Ansible@0
-            displayName: 'Cleanup'
-            inputs:
-              ansibleInterface: 'agentMachine'
-              playbookPathOnAgentMachine: 'iris/ansible/simulation_cleanup.yaml'
-              failOnStdErr: false
-              args: >-
-                -u $(user) --diff -e="pool=/mnt/storage/test_pool" -e="iso_path=/mnt/storage/iso"
-            condition: always()
+  #         - task: Ansible@0
+  #           displayName: 'Cleanup'
+  #           inputs:
+  #             ansibleInterface: 'agentMachine'
+  #             playbookPathOnAgentMachine: 'iris/ansible/simulation_cleanup.yaml'
+  #             failOnStdErr: false
+  #             args: >-
+  #               -u $(user) --diff -e="pool=/mnt/storage/test_pool" -e="iso_path=/mnt/storage/iso"
+  #           condition: always()
